# Generated by Django 4.2.3 on 2023-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
